CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
	role VARCHAR(255) NOT NULL
);

CREATE TABLE category (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    description VARCHAR(255)  NOT NULL
);

create table Task (
	id bigint generated by default as identity,
	date timestamp(6),
	description varchar(255),
	priority smallint check (priority between 0 and 2),
	status smallint check (status between 0 and 2),
	title varchar(255),
	category_id bigint,
	user_id bigint,
	primary key (id)
);

alter table if exists Task add constraint FK13ct62sypv4nnu8o2llrg6hsf foreign key (category_id) references Category;
alter table if exists Task add constraint FKti2fusow0nrhq449y10cp0pxd foreign key (user_id) references users;